### ISSUE TITLE
support choices

### ISSUE THREAD

**Issue by elKokito** [ctil/zargparse#2]
hey nice project!
was wondering how would `choices` be supported
https://docs.python.org/2/library/argparse.html#choices?

**Comment by ctil** [comment]
Thank you! As long as the data is accessible in the ArgumentParser object, it should be possible. I think the [_values function ](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org#functions-for-performing-complex-completions-of-single-words) can be used for the zsh completion.

**Comment by ctil** [comment]
This issue was addressed in #3. Thanks @mabrowning!
